### PR TITLE
Add support for Sweden

### PR DESCRIPTION
**Pull request by aruncveli**
Add `se` to the url regex for top level domain

### CODE REVIEW

**Comment by aruncveli** [comment]
Let me know if I should bump the version too.

Didn't do it yet because I was not sure if you'll have more changes to push as part of a new version.

**Comment by stonecrusher** [comment]
Thanks for the PR!
As I was not able to edit, I made a new push.
- Added support for Swedish URL
- Removed Amazon Smile (doesn't exist anymore)
- Pushed version
https://github.com/stonecrusher/stylus-UserCSS/commit/5b5f099523db6ca325b8919406ce23671b5f81fb

**Comment by aruncveli** [comment]
> As I was not able to edit

Interesting. Is it because I didn't explicitly add you as a reviewer?

**Comment by stonecrusher** [comment]
I have no idea. But also I'm not using github a lot. But there was no "edit" button, neither next to the merge button nor in the commit / commits tab.
Wasn't there an extra checkbox like "Maintainers can make changes?"

**Comment by aruncveli** [comment]
Ah thank you, I see it now. Won't forget that next time.

**Pull request closed without merging**
